<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib uri="jakarta.tags.core" prefix="c"%>
<c:set var="ctx" value="${pageContext.request.contextPath}"/>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Mi pedido | Sabor Express</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@400;500;700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link rel="stylesheet" href="${ctx}/vista/css/styles.css"><link rel="stylesheet" href="${ctx}/vista/css/roles.css?v=22"></head>
<body class="role-page" data-context="${ctx}" data-role="cliente">
<header class="role-header"><a class="brand-link" href="${ctx}/Inicio"><img src="${ctx}/vista/assets/logo.png" alt="Logo Sabor Express"><span>LA BARRA DEL<br><b>SABOR</b></span></a><div class="role-profile">
    <a class="profile-name-link" href="${ctx}/Perfil" title="Ver mi perfil">
        <i class="bi bi-person-circle"></i> ${sessionScope.usuarioLogueado.nombre}
    </a>
    <div class="dropdown client-panel-notification-nav">
        <button class="btn btn-light border-dark rounded-circle position-relative notification-btn-panel" type="button" data-bs-toggle="dropdown" aria-expanded="false" title="Notificaciones" aria-label="Notificaciones">
            <i class="bi bi-bell-fill"></i><span id="panelNotificationBadge" class="notification-badge-panel d-none">0</span>
        </button>
        <div class="dropdown-menu dropdown-menu-end notification-menu-panel p-0">
            <div class="notification-admin-head"><strong>Notificaciones</strong><span id="panelNotificationCount">Sin novedades</span></div>
            <div id="panelClientNotifications" class="notification-admin-list"><div class="text-muted small notification-admin-empty">No hay notificaciones nuevas.</div></div>
            <div class="notification-admin-footer"><button id="panelMarkNotificationsRead" type="button" class="outline-btn btn-sm">Marcar como leídas</button><button id="panelDeleteAllNotifications" type="button" class="outline-btn btn-sm">Eliminar todas</button></div>
        </div>
    </div>
    <a class="btn btn-outline-dark btn-sm" href="${ctx}/Reservas">Reservar mesa</a><a class="btn btn-outline-dark btn-sm" href="${ctx}/Perfil">Mi perfil</a>
    <form novalidate action="${ctx}/CerrarSesion" method="post" class="d-inline"><button type="submit" class="btn btn-outline-dark btn-sm">Salir</button></form>
</div></header>
<main class="container py-4 py-lg-5"><section class="role-hero mb-4"><span class="eyebrow">PEDIDOS EN LÍNEA</span><h1>¡HOLA, ${sessionScope.usuarioLogueado.nombre}!</h1><p class="mb-0">Elige tus favoritos, selecciona mesa o domicilio y envía tu pedido directamente a cocina.</p></section>
<c:if test="${not empty mensaje}"><div class="alert alert-info" role="alert">${mensaje}</div></c:if>
<div class="row g-4"><section class="col-lg-8"><div class="section-title"><span class="eyebrow">MENÚ DIGITAL</span><h2>¿QUÉ VAS A DISFRUTAR?</h2></div><div id="menuGrid" class="row g-3" aria-live="polite"></div></section>
<aside class="col-lg-4"><form novalidate class="order-summary" method="post" action="${ctx}/operaciones" id="pedidoForm"><input type="hidden" name="accion" value="crearCliente"><input type="hidden" name="items" id="items"><h2>MI PEDIDO <span id="cartCount" class="cart-badge">0</span></h2><div id="cartItems" class="cart-items"><p class="text-muted">Todavía no agregas productos.</p></div><div class="order-total"><span>Total</span><strong id="cartTotal">$0</strong></div><fieldset class="mt-3"><legend>Tipo de pedido</legend><div class="d-flex gap-2"><label><input type="radio" name="tipoEntrega" value="MESA" checked> Para mesa</label><label><input type="radio" name="tipoEntrega" value="DOMICILIO"> Domicilio</label></div></fieldset><div id="mesaField" class="mt-3"><label for="mesa" class="form-label">Número de mesa</label><select id="mesa" name="mesa" class="form-select" required><option value="">Cargando mesas...</option></select></div><div id="direccionField" class="mt-3 d-none"><label for="direccion" class="form-label">Dirección de entrega</label><input id="direccion" name="direccion" class="form-control" type="text" placeholder="Barrio, calle y referencias"></div><fieldset class="mt-3"><legend>Método de pago</legend><label class="d-block mb-2"><input type="radio" name="metodoPago" value="EFECTIVO" checked> Efectivo</label><label class="d-block mb-2"><input type="radio" name="metodoPago" value="TARJETA"> Tarjeta</label><label class="d-block mb-2"><input type="radio" name="metodoPago" value="TRANSFERENCIA"> Transferencia</label><small class="text-muted">Los métodos electrónicos funcionan en modo demostración hasta integrar una pasarela real.</small></fieldset><button class="btn btn-primary-brand w-100 mt-4" type="submit">Enviar a cocina</button></form></aside></div>
<section class="mt-5"><div class="section-title"><span class="eyebrow">SEGUIMIENTO</span><h2>MIS PEDIDOS</h2></div><div id="pedidosGrid" class="row g-3"></div></section></main><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="${ctx}/vista/js/roles.js?v=22"></script></body></html>
