<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%><%@taglib uri="jakarta.tags.core" prefix="c"%><c:set var="ctx" value="${pageContext.request.contextPath}"/>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Mesero | Sabor Express</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@400;500;700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="${ctx}/vista/css/styles.css"><link rel="stylesheet" href="${ctx}/vista/css/roles.css"></head>
<body class="role-page" data-context="${ctx}" data-role="mesero"><header class="role-header"><a class="brand-link" href="${ctx}/panel/mesero"><img src="${ctx}/vista/assets/logo.png" alt="Logo Sabor Express"><span>LA BARRA DEL<br><b>SABOR</b></span></a><div class="role-profile">
    <a class="profile-name-link" href="${ctx}/Perfil" title="Ver mi perfil">
        <i class="bi bi-person-circle"></i> ${sessionScope.usuarioLogueado.nombre} ${sessionScope.usuarioLogueado.apellido}
    </a>
    <span class="role-pill">MESERO</span>
    <a class="btn btn-outline-dark btn-sm" href="${ctx}/Perfil">Mi perfil</a>
    <form novalidate action="${ctx}/CerrarSesion" method="post" class="d-inline"><button type="submit" class="btn btn-outline-dark btn-sm">Salir</button></form>
</div></header><main class="container py-4 py-lg-5"><section class="role-hero mb-4"><span class="eyebrow">SERVICIO EN SALÓN</span><h1>¡LISTO PARA ATENDER!</h1><p class="mb-0">Gestiona comandas, pedidos activos e historial desde las pestañas superiores.</p></section><c:if test="${not empty mensaje}"><div class="alert alert-info" role="alert">${mensaje}</div></c:if><nav class="waiter-tabs" aria-label="Secciones del mesero"><button type="button" class="waiter-tab active" data-waiter-tab="nuevo">🍽️ Tomar un pedido</button><button type="button" class="waiter-tab" data-waiter-tab="activos">📦 Mis pedidos activos</button><button type="button" class="waiter-tab" data-waiter-tab="historial">🗂️ Historial de pedidos</button><button type="button" class="waiter-tab" data-waiter-tab="reservas">📅 Reservas de clientes</button></nav><section class="waiter-section active" data-waiter-section="nuevo"><div class="row g-4"><section class="col-lg-8"><div class="section-title"><span class="eyebrow">MENÚ DISPONIBLE</span><h2>NUEVA COMANDA</h2></div><div id="menuGrid" class="row g-3"></div></section><aside class="col-lg-4"><form novalidate class="order-summary" method="post" action="${ctx}/operaciones" id="pedidoForm"><input type="hidden" name="accion" value="crearMesero"><input type="hidden" name="items" id="items"><h2>COMANDA <span id="cartCount" class="cart-badge">0</span></h2><label for="mesa" class="form-label">Mesa</label><select id="mesa" name="mesa" class="form-select" required><option value="">Cargando mesas...</option></select><div id="cartItems" class="cart-items mt-3"><p class="text-muted">Selecciona productos.</p></div><div class="order-total"><span>Total</span><strong id="cartTotal">$0</strong></div><button class="btn btn-primary-brand w-100 mt-4" type="submit">Enviar a cocina</button></form></aside></div></section><section class="waiter-section" data-waiter-section="activos"><div class="section-title"><span class="eyebrow">SEGUIMIENTO</span><h2>MIS PEDIDOS ACTIVOS</h2></div><div id="pedidosGrid" class="row g-3"></div></section><section class="waiter-section" data-waiter-section="historial"><div class="section-title"><span class="eyebrow">COMANDAS FINALIZADAS</span><h2>HISTORIAL DE PEDIDOS</h2></div><div id="historialPedidosGrid" class="row g-3"><p class="text-muted">Selecciona esta pestaña para cargar el historial.</p></div></section><section class="waiter-section" data-waiter-section="reservas"><div class="section-title"><span class="eyebrow">ATENCIÓN EN SALÓN</span><h2>RESERVAS DE CLIENTES</h2></div><div class="panel-reserva-role"><p>Consulta las reservas y confirma la llegada del cliente cuando se presente en el local.</p><a class="btn btn-primary-brand" href="${ctx}/Reservas">Ver reservas de clientes</a></div></section></main><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="${ctx}/vista/js/roles.js"></script></body></html>
