<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%><%@taglib uri="jakarta.tags.core" prefix="c"%><c:set var="ctx" value="${pageContext.request.contextPath}"/>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Repartidor | Sabor Express</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@400;500;700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link rel="stylesheet" href="${ctx}/vista/css/styles.css"><link rel="stylesheet" href="${ctx}/vista/css/roles.css?v=24"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"></head>
<body class="role-page" data-context="${ctx}" data-role="repartidor"><header class="role-header"><a class="brand-link" href="${ctx}/panel/repartidor"><img src="${ctx}/vista/assets/logo.png" alt="Logo Sabor Express"><span>LA BARRA DEL<br><b>SABOR</b></span></a><div class="role-profile align-items-center gap-2">
    <button type="button" class="btn btn-outline-dark btn-sm" id="btnDisponibilidadRepartidor" aria-pressed="false">🟢 En línea</button><button type="button" class="btn btn-outline-dark btn-sm" id="btnTurnoRepartidor"><i class="bi bi-cash-stack me-1"></i>Resumen de turno</button>
    <a class="profile-name-link" href="${ctx}/Perfil" title="Ver mi perfil"><i class="bi bi-person-circle"></i> <i class="bi bi-bicycle-fill text-warning me-1"></i>${sessionScope.usuarioLogueado.nombre} ${sessionScope.usuarioLogueado.apellido}</a>
    <a class="btn btn-outline-dark btn-sm" href="${ctx}/Perfil">Mi perfil</a>
    <form novalidate action="${ctx}/CerrarSesion" method="post" class="d-inline"><button type="submit" class="btn btn-outline-dark btn-sm">Salir</button></form>
</div></header><main class="container repartidor-main py-4 py-lg-5"><section class="role-hero mb-4"><span class="eyebrow">ENTREGAS A DOMICILIO</span><h1>RUTA DE HOY</h1><p class="mb-1">Elige un pedido listo, inicia la ruta y confirma la entrega al finalizar.</p><small class="base-address-label">📍 Base: Cra. 3 #3-34, Guaduas, Cundinamarca</small></section><c:if test="${not empty mensaje}"><div class="alert alert-info" role="alert">${mensaje}</div></c:if><section><div class="section-title"><span class="eyebrow">DOMICILIOS</span><h2>DISPONIBLES Y EN CAMINO</h2></div><div class="row g-4 align-items-start repartidor-layout"><aside class="col-lg-3" id="rutaPanelWrap"></aside><div class="col-lg-9"><div id="deliveryTabs"></div><div id="pedidosGrid" class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-4 mt-1 delivery-grid"></div></div></div></section><section class="mt-5"><div class="section-title"><span class="eyebrow">HISTORIAL</span><h2>PEDIDOS REALIZADOS POR MÍ</h2></div><div id="repartidorHistory" class="row g-3"><p class="text-muted">Cargando historial...</p></div></section></main>
<div class="modal fade" id="pinEntregaModal" tabindex="-1" aria-labelledby="pinEntregaLabel" aria-hidden="true">
 <div class="modal-dialog modal-dialog-centered modal-sm"><form novalidate class="modal-content neo-modal" method="post" action="${ctx}/operaciones" id="pinEntregaForm"><div class="modal-header"><h5 class="modal-title" id="pinEntregaLabel">PIN de entrega</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body"><p class="small text-muted">Solicita al cliente el código de 4 dígitos para confirmar la entrega.</p><input type="hidden" name="accion" value="estado"><input type="hidden" name="cambio" value="entregado"><input type="hidden" name="pedido" id="pinPedido"><label for="pinEntrega" class="form-label fw-bold">PIN</label><input id="pinEntrega" name="pinEntrega" class="form-control text-center fw-bold fs-3" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" minlength="4" required autocomplete="one-time-code"></div><div class="modal-footer"><button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary-brand">Confirmar entrega</button></div></form></div>
</div>
<div class="modal fade" id="cancelarDomicilioModal" tabindex="-1" aria-labelledby="cancelarDomicilioLabel" aria-hidden="true">
 <div class="modal-dialog modal-dialog-centered"><form novalidate class="modal-content neo-modal" method="post" action="${ctx}/operaciones" id="cancelarDomicilioForm"><div class="modal-header"><h5 class="modal-title" id="cancelarDomicilioLabel">Cancelar pedido</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body"><input type="hidden" name="accion" value="cancelarDomicilio"><input type="hidden" name="pedido" id="cancelarPedido"><label for="motivoCancelacion" class="form-label fw-bold">Motivo obligatorio</label><select class="form-select" id="motivoCancelacion" name="motivoCancelacion" required><option value="">Selecciona un motivo</option><option value="Cliente no responde llamadas/timbre">Cliente no responde llamadas/timbre</option><option value="Dirección fuera de zona o incorrecta">Dirección fuera de zona o incorrecta</option><option value="Pedido dañado o derramado">Pedido dañado o derramado</option><option value="Cliente cancela la entrega">Cliente cancela la entrega</option><option value="Otra incidencia">Otra incidencia</option></select><div id="otraIncidenciaWrap" class="mt-3 d-none"><label for="detalleIncidencia" class="form-label fw-bold">Detalle de la incidencia</label><textarea class="form-control" id="detalleIncidencia" name="detalleIncidencia" rows="4" maxlength="500" placeholder="Describe qué ocurrió..."></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Volver</button><button type="submit" class="btn btn-danger">Registrar cancelación</button></div></form></div>
</div>
<div class="modal fade" id="turnoRepartidorModal" tabindex="-1" aria-labelledby="turnoRepartidorLabel" aria-hidden="true">
 <div class="modal-dialog modal-dialog-centered"><div class="modal-content turno-modal"><div class="modal-header"><h5 class="modal-title" id="turnoRepartidorLabel">RESUMEN DE CAJA · TURNO</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body"><div class="turno-stats"><div class="turno-stat"><small>ENTREGAS HOY</small><strong id="turnoEntregas">0</strong></div><div class="turno-stat"><small>EFECTIVO RECAUDADO</small><strong id="turnoEfectivo">$0</strong></div><div class="turno-stat"><small>VALOR A LIQUIDAR</small><strong id="turnoLiquidar">$0</strong></div></div></div></div></div>
</div>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="${ctx}/vista/js/roles.js?v=24"></script></body></html>
